#!/usr/local/bin/python3
m random import randrange
from math import ceil

random=randrange(50)
print(random) #pour test
mise=int(input("Choisissez une somme à miser : "))
choix=int(input("Choisissez un nombre entre 0 et 49 : "))
if (choix==random):
    print("Bravo, vous avez gagné ", mise*3, "€ !")
elif (random % 2) == 0 and (choix % 2) == 0:
    print("Bravo, vous avez gagné ", mise+(mise/2), "€ !")
elif (random % 2) == 1 and (choix % 2) == 1:
    print("Bravo, vous avez gagné ", mise+(mise/2), "€ !")
else:
    print("Vous avez perdu :( ")
